Repository alejandrohdezma/http4s-munit, pull requests merged in 2021-02, with the labels that each got.

#17 Update sbt to 1.4.7
  project/build.properties
Labels: autorebase:opt-in, scala-steward

#18 Update http4s-async-http-client, ... to 0.21.17
  build.sbt
Labels: autorebase:opt-in, scala-steward

#19 Update testcontainers-scala-munit to 0.38.9
  build.sbt
Labels: autorebase:opt-in, scala-steward

#21 Update testcontainers-scala-munit to 0.39.0
  build.sbt
Labels: autorebase:opt-in, scala-steward

#22 Update mdoc_2.12.12, mdoc_2.13, sbt-mdoc to 2.2.17
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#23 Update sbt-ci to 1.4.0
  .github/workflows/auto-rebase.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/scala-steward.yml
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#24 Handle fail exceptions and add response body as clues
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
Labels: enhancement

#16 Update munit-cats-effect-2 to 0.13.0
  build.sbt
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
Labels: autorebase:opt-in, scala-steward

#25 Ensure URI can be obtained from a wider variety of containers
  modules/http4s-munit-testcontainers/src/main/scala/munit/LowPrecedenceContainer2Uri.scala
Labels: enhancement

#20 Update http4s-async-http-client, ... to 0.21.18
  build.sbt
Labels: autorebase:opt-in, scala-steward

#26 Update testcontainers-scala-munit to 0.39.1
  build.sbt
Labels: autorebase:opt-in, scala-steward

#27 Update http4s-async-http-client, ... to 0.21.19
  build.sbt
Labels: autorebase:non-rebaseable, autorebase:opt-in, scala-steward

#28 Update munit to 0.7.22
  build.sbt
Labels: autorebase:opt-in, scala-steward

#30 Update munit-cats-effect-2 to 0.13.1
  build.sbt
Labels: autorebase:opt-in, scala-steward

#29 Update mdoc_2.12.12, mdoc_2.13, sbt-mdoc to 2.2.18
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#31 Allow pretty printing JSON bodies on failed assertions
  build.sbt
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
  modules/http4s-munit-testcontainers/src/test/resources/db.json
  modules/http4s-munit-testcontainers/src/test/scala/munit/DummyHttpContainer.scala
  modules/http4s-munit-testcontainers/src/test/scala/munit/HttpFromContainerSuiteSuite.scala
Labels: enhancement

#32 Fix error when highlighting JSON output
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
Labels: bug

#33 Update testcontainers-scala-munit to 0.39.2
  build.sbt
Labels: autorebase:opt-in, scala-steward

#34 Modify regex for pretty printing negative and floating points numbers
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
Labels: bug

#35 Update testcontainers-scala-munit to 0.39.3
  build.sbt
Labels: autorebase:opt-in, scala-steward
