Repository alejandrohdezma/http4s-munit, pull requests merged in 2021-03, with the labels that each got.

#36 Update sbt-scalafix to 0.9.26
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#38 Update sbt-scalafmt-defaults to 0.4.1
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#39 Update http4s-async-http-client, ... to 0.21.20
  build.sbt
Labels: autorebase:opt-in, scala-steward

#37 Update sbt-ci to 1.4.1
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#40 Add repetition feature for tests
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
  modules/http4s-munit-testcontainers/src/test/scala/munit/HttpFromContainerSuiteSuite.scala
Labels: enhancement

#41 Propagate features in `HttpFromContainerSuite` to other suites
  build.sbt
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sAuthedRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sHttpRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sHttpRoutesSuiteSuite.scala
Labels: enhancement

#47 Update sbt-github-header, sbt-github-mdoc to 0.9.1
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#48 Update sbt to 1.4.8
  project/build.properties
Labels: autorebase:opt-in, scala-steward

#43 Make `HttpFromContainerSuite` extend `HttpSuite`
  build.sbt
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
  modules/http4s-munit-testcontainers/src/main/scala/munit/LowPrecedenceContainer2Uri.scala
  modules/http4s-munit-testcontainers/src/test/scala/munit/HttpFromContainerSuiteSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
  modules/http4s-munit/src/test/scala/munit/HttpSuiteSuite.scala
Labels: enhancement

#44 Revamp ScalaDocs
  modules/http4s-munit-testcontainers/src/main/scala/munit/HttpFromContainerSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sAuthedRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sHttpRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
Labels: documentation

#45 Unify prefix names for overridable members
  modules/http4s-munit/src/main/scala/munit/Http4sAuthedRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sHttpRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sAuthedRoutesSuiteSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sHttpRoutesSuiteSuite.scala
Labels: enhancement

#46 Generalise `Http4sSuite` even more
  modules/http4s-munit/src/main/scala/munit/Http4sAuthedRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sHttpRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
Labels: enhancement

#42 Add num repetitions and max concurrent parameters configuration
  modules/http4s-munit/src/main/scala/munit/Http4sMunitConfig.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sAuthedRoutesSuiteSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sHttpRoutesSuiteSuite.scala
Labels: enhancement

#49 Create suite for ensuring test names are correctly and logs contain body
  build.sbt
  modules/http4s-munit/src/test/scala/munit/LogsSuite.scala
Labels: tests

#50 Fix scaladoc generation error
  modules/http4s-munit/src/main/scala/munit/Http4sAuthedRoutesSuite.scala
Labels: bug

#52 Fix max parallel env variable name
  modules/http4s-munit/src/main/scala/munit/Http4sMunitConfig.scala
Labels: bug

#54 Update sbt-ci-release to 1.5.6
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#53 Allow adding follow-up requests to tests
  build.sbt
  modules/http4s-munit-testcontainers/src/test/resources/db.json
  modules/http4s-munit-testcontainers/src/test/scala/munit/HttpFromContainerSuiteSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sAuthedRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sHttpRoutesSuite.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sAuthedRoutesSuiteSuite.scala
  modules/http4s-munit/src/test/scala/munit/Http4sHttpRoutesSuiteSuite.scala
  modules/http4s-munit/src/test/scala/munit/LogsSuite.scala
  modules/http4s-munit/src/test/scala/munit/ParallelSuite.scala
Labels: enhancement

#57 Update sbt-github-header, sbt-github-mdoc to 0.9.2
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#56 Update sbt-ci to 1.5.0
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/scala-steward.yml
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#58 Update sbt-ci to 1.6.0
  .github/settings.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/draft-next-release.yml
  .github/workflows/release.yml
  project/plugins.sbt
Labels: autorebase:opt-in, scala-steward

#55 Consistency
  modules/http4s-munit/src/main/scala/munit/Http4sMUnitConfig.scala
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
Labels: enhancement

#60 Send correct location to `http4sMUnitNameCreator`
  modules/http4s-munit/src/main/scala/munit/Http4sSuite.scala
Labels: bug
