Repository alejandrohdezma/http4s-munit, pull requests merged in 2022-11, with the labels that each got.

#282 Fix scala code format in docs
  docs/README.md
Labels: :beetle: bug, :balance_scale: XS

#283 Add default empty value to `HttpSuite#baseUri`
  modules/http4s-munit/src/main/scala/munit/HttpSuite.scala
  modules/http4s-munit/src/test/scala/munit/HttpSuiteNoBaseUriSuite.scala
  modules/http4s-munit/src/test/scala/munit/LogsSuite.scala
Labels: :rocket: feature, :balance_scale: S

#284 Reword default test name where there are following requests
  modules/http4s-munit/src/main/scala/munit/Http4sMUnitDefaults.scala
  modules/http4s-munit/src/test/scala/munit/LogsSuite.scala
Labels: :rocket: feature, :balance_scale: XXS
